title: CyberPrivacyProtecTech
description: "Sophisticated and Tailored Cyber Privacy and CyberSecurity Consulting Services"
baseurl: ""
url: "https://cyberprivacy.tech"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
google_site_verification: nugRD-c5ncylSDYGIhWEtoZjSlK3mTw1j5zR9NUO3kc

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin # Added for multi-language support

languages:
  - en
  - fr
  - pt

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
      lang: "fr"
      keywords: ""

github_username: alexeinazarov
google_analytics: G-91WCLQETXM

exclude:
  - Gemfile.lock
  - README.md
  - Rakefile
  - .gitignore
  - .github/
  - vendor/
  - node_modules/
  - .DS_Store
  - .jekyll-cache/
  - _site/
  - feed.xml

include:
  - sitemap.xml
  - assets/images/logo.webp
  - favicon.ico

minify_html:
  enable: true

compress:
  enable: true

assets:
  cache: true

keywords: "cybersecurity, privacy, ..."

# Custom settings for multi-language support
locales:
  en:
    recent_posts: "Recent Posts"
  fr:
    recent_posts: "Articles Récents"
  pt:
    recent_posts: "Postagens Recentes"
